ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER ADMIN IDENTIFIED BY admin123 ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE, DBA TO ADMIN;
ALTER USER ADMIN QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO ADMIN;
GRANT CREATE TABLE TO ADMIN;
GRANT CREATE VIEW TO ADMIN;
GRANT CREATE SEQUENCE TO ADMIN;
GRANT CREATE PROCEDURE TO ADMIN;
GRANT CREATE TRIGGER TO ADMIN;
GRANT CREATE SYNONYM TO ADMIN;
GRANT CREATE TYPE TO ADMIN;
GRANT CREATE MATERIALIZED VIEW TO ADMIN;
GRANT UNLIMITED TABLESPACE TO ADMIN;